/***********************************************************************/
/*                                                                     */
/*  FILE        :course2.c                                             */
/*  DATE        :Thu, Dec 01, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
