/***********************************************************************/
/*                                                                     */
/*  FILE        :hwsetup.c                                             */
/*  DATE        :Thu, Dec 01, 2022                                     */
/*  DESCRIPTION :Hardware Setup file                                   */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  



#include "iodefine.h"
#ifdef __cplusplus
extern "C" {
#endif
extern void HardwareSetup(void);
#ifdef __cplusplus
}
#endif

void HardwareSetup(void)
{
/*
  BSC.CSCR.BYTE = 0;
  BSC.CSCR.BIT.CS7E = 1;
  BSC.CSCR.BIT.CS6E = 1;
  BSC.CSCR.BIT.CS5E = 1;
  BSC.CSCR.BIT.CS4E = 1;
*/
}
