/***********************************************************************/
/*                                                                     */
/*  FILE        :sbrk.h                                                */
/*  DATE        :Thu, Dec 01, 2022                                     */
/*  DESCRIPTION :Header file of sbrk file                              */
/*  CPU TYPE    :H8/3052F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
/* size of area managed by sbrk */
#define HEAPSIZE 0x420
